SET @DATABASE_NAME = 'mantisbt';

SELECT  CONCAT('ALTER TABLE ', table_name, ' ENGINE=InnoDB;') AS sql_statements
FROM    information_schema.tables AS tb
WHERE   table_schema = @DATABASE_NAME
AND     `ENGINE` = 'MyISAM'
AND     `TABLE_TYPE` = 'BASE TABLE'
ORDER BY table_name DESC;

ALTER TABLE mantis_project_hierarchy_table ADD COLUMN _id INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (_id);
ALTER TABLE mantis_tag_table DROP PRIMARY KEY;
ALTER TABLE mantis_tag_table CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE user_id user_id INT NOT NULL, CHANGE date_created date_created INT NOT NULL, CHANGE date_updated date_updated INT NOT NULL;
CREATE UNIQUE INDEX `UNIQUE` ON mantis_tag_table (id, name);
ALTER TABLE mantis_tag_table ADD PRIMARY KEY (id);

-- "C:\xampp\php\php.exe" "C:\xampp\htdocs\mantis5\app\console" "--ansi" "doctrine:schema:update" "--dump-sql"
ALTER TABLE mantis_bug_table CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE project_id project_id INT NOT NULL, CHANGE reporter_id reporter_id INT NOT NULL, CHANGE handler_id handler_id INT NOT NULL, CHANGE duplicate_id duplicate_id INT NOT NULL, CHANGE priority priority SMALLINT NOT NULL, CHANGE severity severity SMALLINT NOT NULL, CHANGE reproducibility reproducibility SMALLINT NOT NULL, CHANGE status status SMALLINT NOT NULL, CHANGE resolution resolution SMALLINT NOT NULL, CHANGE projection projection SMALLINT NOT NULL, CHANGE eta eta SMALLINT NOT NULL, CHANGE bug_text_id bug_text_id INT NOT NULL, CHANGE os os VARCHAR(32) NOT NULL, CHANGE os_build os_build VARCHAR(32) NOT NULL, CHANGE platform platform VARCHAR(32) NOT NULL, CHANGE version version VARCHAR(64) NOT NULL, CHANGE fixed_in_version fixed_in_version VARCHAR(64) NOT NULL, CHANGE build build VARCHAR(32) NOT NULL, CHANGE profile_id profile_id INT NOT NULL, CHANGE view_state view_state SMALLINT NOT NULL, CHANGE summary summary VARCHAR(128) NOT NULL, CHANGE sponsorship_total sponsorship_total INT NOT NULL, CHANGE sticky sticky TINYINT(1) NOT NULL, CHANGE target_version target_version VARCHAR(64) NOT NULL, CHANGE category_id category_id INT NOT NULL, CHANGE date_submitted date_submitted INT NOT NULL, CHANGE due_date due_date INT NOT NULL, CHANGE last_updated last_updated INT NOT NULL;
ALTER TABLE mantis_bug_file_table CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE bug_id bug_id INT NOT NULL, CHANGE title title VARCHAR(250) NOT NULL, CHANGE description description VARCHAR(250) NOT NULL, CHANGE diskfile diskfile VARCHAR(250) NOT NULL, CHANGE filename filename VARCHAR(250) NOT NULL, CHANGE folder folder VARCHAR(250) NOT NULL, CHANGE filesize filesize INT NOT NULL, CHANGE file_type file_type VARCHAR(250) NOT NULL, CHANGE date_added date_added INT NOT NULL, CHANGE user_id user_id INT NOT NULL;
ALTER TABLE mantis_bug_history_table CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE user_id user_id INT NOT NULL, CHANGE bug_id bug_id INT NOT NULL, CHANGE type type SMALLINT NOT NULL, CHANGE date_modified date_modified INT NOT NULL;
ALTER TABLE mantis_bug_monitor_table CHANGE user_id user_id INT NOT NULL, CHANGE bug_id bug_id INT NOT NULL;
ALTER TABLE mantis_bugnote_table CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE bug_id bug_id INT NOT NULL, CHANGE reporter_id reporter_id INT NOT NULL, CHANGE bugnote_text_id bugnote_text_id INT NOT NULL, CHANGE view_state view_state SMALLINT NOT NULL, CHANGE note_type note_type INT DEFAULT NULL, CHANGE note_attr note_attr VARCHAR(250) DEFAULT NULL, CHANGE time_tracking time_tracking INT NOT NULL, CHANGE last_modified last_modified INT NOT NULL, CHANGE date_submitted date_submitted INT NOT NULL;
ALTER TABLE mantis_bugnote_text_table CHANGE id id INT AUTO_INCREMENT NOT NULL;
ALTER TABLE mantis_bug_relationship_table CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE source_bug_id source_bug_id INT NOT NULL, CHANGE destination_bug_id destination_bug_id INT NOT NULL, CHANGE relationship_type relationship_type SMALLINT NOT NULL;
ALTER TABLE mantis_bug_revision_table CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE bug_id bug_id INT NOT NULL, CHANGE bugnote_id bugnote_id INT NOT NULL, CHANGE user_id user_id INT NOT NULL, CHANGE type type INT NOT NULL, CHANGE timestamp timestamp INT NOT NULL;
ALTER TABLE mantis_bug_tag_table CHANGE bug_id bug_id INT NOT NULL, CHANGE tag_id tag_id INT NOT NULL, CHANGE user_id user_id INT NOT NULL, CHANGE date_attached date_attached INT NOT NULL;
ALTER TABLE mantis_bug_text_table CHANGE id id INT AUTO_INCREMENT NOT NULL;
ALTER TABLE mantis_category_table CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE project_id project_id INT NOT NULL, CHANGE user_id user_id INT NOT NULL, CHANGE name name VARCHAR(128) NOT NULL, CHANGE status status INT NOT NULL;
ALTER TABLE mantis_config_table CHANGE project_id project_id INT NOT NULL, CHANGE user_id user_id INT NOT NULL, CHANGE access_reqd access_reqd INT DEFAULT NULL, CHANGE type type INT DEFAULT NULL;
ALTER TABLE mantis_custom_field_table CHANGE name name VARCHAR(64) NOT NULL, CHANGE type type SMALLINT NOT NULL, CHANGE default_value default_value VARCHAR(255) NOT NULL, CHANGE valid_regexp valid_regexp VARCHAR(255) NOT NULL, CHANGE access_level_r access_level_r SMALLINT NOT NULL, CHANGE access_level_rw access_level_rw SMALLINT NOT NULL, CHANGE length_min length_min INT NOT NULL, CHANGE length_max length_max INT NOT NULL, CHANGE require_report require_report TINYINT(1) NOT NULL, CHANGE require_update require_update TINYINT(1) NOT NULL, CHANGE display_report display_report TINYINT(1) NOT NULL, CHANGE display_update display_update TINYINT(1) NOT NULL, CHANGE require_resolved require_resolved TINYINT(1) NOT NULL, CHANGE display_resolved display_resolved TINYINT(1) NOT NULL, CHANGE display_closed display_closed TINYINT(1) NOT NULL, CHANGE require_closed require_closed TINYINT(1) NOT NULL, CHANGE filter_by filter_by TINYINT(1) NOT NULL;
ALTER TABLE mantis_custom_field_project_table CHANGE field_id field_id INT NOT NULL, CHANGE project_id project_id INT NOT NULL, CHANGE sequence sequence SMALLINT NOT NULL;
ALTER TABLE mantis_custom_field_string_table CHANGE field_id field_id INT NOT NULL, CHANGE bug_id bug_id INT NOT NULL, CHANGE value value VARCHAR(255) NOT NULL;
ALTER TABLE mantis_email_table CHANGE email_id email_id INT AUTO_INCREMENT NOT NULL, CHANGE email email VARCHAR(64) NOT NULL, CHANGE subject subject VARCHAR(250) NOT NULL, CHANGE submitted submitted INT NOT NULL;
ALTER TABLE mantis_filters_table CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE user_id user_id INT NOT NULL, CHANGE project_id project_id INT NOT NULL, CHANGE name name VARCHAR(64) NOT NULL;
ALTER TABLE mantis_news_table CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE project_id project_id INT NOT NULL, CHANGE poster_id poster_id INT NOT NULL, CHANGE view_state view_state SMALLINT NOT NULL, CHANGE announcement announcement TINYINT(1) NOT NULL, CHANGE headline headline VARCHAR(64) NOT NULL, CHANGE last_modified last_modified INT NOT NULL, CHANGE date_posted date_posted INT NOT NULL;
ALTER TABLE mantis_plugin_table CHANGE basename basename VARCHAR(40) NOT NULL, CHANGE enabled enabled TINYINT(1) NOT NULL, CHANGE protected protected TINYINT(1) NOT NULL, CHANGE priority priority INT NOT NULL;
ALTER TABLE mantis_project_table CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(128) NOT NULL, CHANGE status status SMALLINT NOT NULL, CHANGE enabled enabled TINYINT(1) NOT NULL, CHANGE view_state view_state SMALLINT NOT NULL, CHANGE access_min access_min SMALLINT NOT NULL, CHANGE file_path file_path VARCHAR(250) NOT NULL, CHANGE category_id category_id INT NOT NULL, CHANGE inherit_global inherit_global INT NOT NULL;
ALTER TABLE mantis_project_file_table CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE project_id project_id INT NOT NULL, CHANGE title title VARCHAR(250) NOT NULL, CHANGE description description VARCHAR(250) NOT NULL, CHANGE diskfile diskfile VARCHAR(250) NOT NULL, CHANGE filename filename VARCHAR(250) NOT NULL, CHANGE folder folder VARCHAR(250) NOT NULL, CHANGE filesize filesize INT NOT NULL, CHANGE file_type file_type VARCHAR(250) NOT NULL, CHANGE date_added date_added INT NOT NULL, CHANGE user_id user_id INT NOT NULL;
ALTER TABLE mantis_project_hierarchy_table CHANGE child_id child_id INT NOT NULL, CHANGE parent_id parent_id INT NOT NULL, CHANGE inherit_parent inherit_parent INT NOT NULL;
ALTER TABLE mantis_project_user_list_table CHANGE project_id project_id INT NOT NULL, CHANGE user_id user_id INT NOT NULL, CHANGE access_level access_level SMALLINT NOT NULL;
ALTER TABLE mantis_project_version_table CHANGE project_id project_id INT NOT NULL, CHANGE version version VARCHAR(64) NOT NULL, CHANGE released released TINYINT(1) NOT NULL, CHANGE obsolete obsolete TINYINT(1) NOT NULL, CHANGE date_order date_order INT NOT NULL;
ALTER TABLE mantis_sponsorship_table CHANGE bug_id bug_id INT NOT NULL, CHANGE user_id user_id INT NOT NULL, CHANGE amount amount INT NOT NULL, CHANGE logo logo VARCHAR(128) NOT NULL, CHANGE url url VARCHAR(128) NOT NULL, CHANGE paid paid TINYINT(1) NOT NULL, CHANGE date_submitted date_submitted INT NOT NULL, CHANGE last_updated last_updated INT NOT NULL;
ALTER TABLE mantis_tag_table CHANGE id id INT NOT NULL, CHANGE name name VARCHAR(100) NOT NULL, CHANGE user_id user_id INT NOT NULL, CHANGE date_created date_created INT NOT NULL, CHANGE date_updated date_updated INT NOT NULL;
ALTER TABLE mantis_tokens_table CHANGE timestamp timestamp INT NOT NULL, CHANGE expiry expiry INT NOT NULL;
ALTER TABLE mantis_user_table CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE username username VARCHAR(32) NOT NULL, CHANGE realname realname VARCHAR(64) NOT NULL, CHANGE email email VARCHAR(64) NOT NULL, CHANGE password password VARCHAR(32) NOT NULL, CHANGE enabled enabled TINYINT(1) NOT NULL, CHANGE protected protected TINYINT(1) NOT NULL, CHANGE access_level access_level SMALLINT NOT NULL, CHANGE login_count login_count INT NOT NULL, CHANGE lost_password_request_count lost_password_request_count SMALLINT NOT NULL, CHANGE failed_login_count failed_login_count SMALLINT NOT NULL, CHANGE cookie_string cookie_string VARCHAR(64) NOT NULL, CHANGE last_visit last_visit INT NOT NULL, CHANGE date_created date_created INT NOT NULL;
ALTER TABLE mantis_user_pref_table CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE user_id user_id INT NOT NULL, CHANGE project_id project_id INT NOT NULL, CHANGE default_profile default_profile INT NOT NULL, CHANGE default_project default_project INT NOT NULL, CHANGE refresh_delay refresh_delay INT NOT NULL, CHANGE redirect_delay redirect_delay INT NOT NULL, CHANGE bugnote_order bugnote_order VARCHAR(4) NOT NULL, CHANGE email_on_new email_on_new TINYINT(1) NOT NULL, CHANGE email_on_assigned email_on_assigned TINYINT(1) NOT NULL, CHANGE email_on_feedback email_on_feedback TINYINT(1) NOT NULL, CHANGE email_on_resolved email_on_resolved TINYINT(1) NOT NULL, CHANGE email_on_closed email_on_closed TINYINT(1) NOT NULL, CHANGE email_on_reopened email_on_reopened TINYINT(1) NOT NULL, CHANGE email_on_bugnote email_on_bugnote TINYINT(1) NOT NULL, CHANGE email_on_status email_on_status TINYINT(1) NOT NULL, CHANGE email_on_priority email_on_priority TINYINT(1) NOT NULL, CHANGE email_on_priority_min_severity email_on_priority_min_severity SMALLINT NOT NULL, CHANGE email_on_status_min_severity email_on_status_min_severity SMALLINT NOT NULL, CHANGE email_on_bugnote_min_severity email_on_bugnote_min_severity SMALLINT NOT NULL, CHANGE email_on_reopened_min_severity email_on_reopened_min_severity SMALLINT NOT NULL, CHANGE email_on_closed_min_severity email_on_closed_min_severity SMALLINT NOT NULL, CHANGE email_on_resolved_min_severity email_on_resolved_min_severity SMALLINT NOT NULL, CHANGE email_on_feedback_min_severity email_on_feedback_min_severity SMALLINT NOT NULL, CHANGE email_on_assigned_min_severity email_on_assigned_min_severity SMALLINT NOT NULL, CHANGE email_on_new_min_severity email_on_new_min_severity SMALLINT NOT NULL, CHANGE email_bugnote_limit email_bugnote_limit SMALLINT NOT NULL, CHANGE language language VARCHAR(32) NOT NULL, CHANGE timezone timezone VARCHAR(32) NOT NULL;
ALTER TABLE mantis_user_print_pref_table CHANGE user_id user_id INT AUTO_INCREMENT NOT NULL;
ALTER TABLE mantis_user_profile_table CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE user_id user_id INT NOT NULL, CHANGE platform platform VARCHAR(32) NOT NULL, CHANGE os os VARCHAR(32) NOT NULL, CHANGE os_build os_build VARCHAR(32) NOT NULL;
ALTER TABLE mantis_plugin_table CHANGE basename basename VARCHAR(40) NOT NULL;